// Generated by scripts/import-dreamskin-themes.mjs; do not edit by hand.
export const importedDesktopSkins = [
    {
        "id": "wukong",
        "assetId": "wukong",
        "sourceVersionId": "ver_ab667004dad5bfec326d",
        "name": "悟空（WUKONG）",
        "publisher": "JamesOpsLab",
        "license": "MIT",
        "appearance": "dark",
        "backgroundUrl": "/desktop-skins/wukong/background.4b821671aaed33e9.webp",
        "focusX": 0,
        "focusY": 0.5,
        "colors": {
            "background": "#131313",
            "panel": "#1d1e1d",
            "panelAlt": "#2a2a2a",
            "accent": "#f6c696",
            "accentAlt": "#f7cea5",
            "secondary": "#2c7c95",
            "highlight": "#f8d4b0",
            "text": "#f0f0f0",
            "muted": "#939393",
            "line": "#3f3f3f"
        }
    },
    {
        "id": "firefly",
        "assetId": "firefly",
        "sourceVersionId": "ver_db0516661b1ac5bc1590",
        "name": "firefly",
        "publisher": "1xifengdeyouxi",
        "license": "MIT",
        "appearance": "light",
        "backgroundUrl": "/desktop-skins/firefly/background.5c0ab4b5711d9c2c.webp",
        "focusX": 0.08,
        "focusY": 0.5,
        "colors": {
            "background": "rgba(230, 239, 240, 0.04)",
            "panel": "rgba(189, 204, 209, 0.26)",
            "panelAlt": "rgba(224, 237, 240, 0.68)",
            "accent": "#f59e0b",
            "accentAlt": "#e63983",
            "secondary": "#08a9b9",
            "highlight": "#fff0c7",
            "text": "#263b42",
            "muted": "#4f6971",
            "line": "rgba(78, 121, 131, 0.38)"
        }
    },
    {
        "id": "evaWarm",
        "assetId": "eva-warm",
        "sourceVersionId": "ver_f836b53d9df32ab8ecf7",
        "name": "Claude EVA 暖奶油",
        "publisher": "TunaTung",
        "license": "MIT",
        "appearance": "light",
        "backgroundUrl": "/desktop-skins/eva-warm/background.4174f45e0a2ccb41.webp",
        "focusX": 0.44,
        "focusY": 0.38,
        "colors": {
            "background": "#F4F1EA",
            "panel": "#FAF7F0",
            "panelAlt": "#EFEAE0",
            "accent": "#D97757",
            "accentAlt": "#E28C6E",
            "secondary": "#8B95A1",
            "highlight": "#F5E7DC",
            "text": "#3D3A33",
            "muted": "#8A8477",
            "line": "#E3DCD0"
        }
    },
    {
        "id": "meadowSky",
        "assetId": "meadow-sky",
        "sourceVersionId": "ver_2da9f883d79a7bb3864b",
        "name": "草地天空",
        "publisher": "FerdinandHu",
        "license": "CC BY 4.0",
        "appearance": "dark",
        "backgroundUrl": "/desktop-skins/meadow-sky/background.27ddd091d6de0346.webp",
        "focusX": 0.5,
        "focusY": 0.5,
        "colors": {
            "background": "#131413",
            "panel": "#1d1e1d",
            "panelAlt": "#2a2b29",
            "accent": "#718636",
            "accentAlt": "#859752",
            "secondary": "#5a7e9a",
            "highlight": "#95a468",
            "text": "#dbdbdb",
            "muted": "#ffffff",
            "line": "#3f403f"
        }
    }
] as const;
