ALTER TABLE "AppDelegation" ADD COLUMN "protocol" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "AppChatWorker" ADD COLUMN "engines" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "AppChatTurn" ADD COLUMN "minimumProtocol" INTEGER NOT NULL DEFAULT 1;
