// Curated GPT Image 2 reference examples.
import type { ImageSourcePropType } from 'react-native';

export const EXTRA_IMAGE_STYLE_PREVIEW_ASSETS: Record<string, ImageSourcePropType> = {
    "reference-tiramisu/vintage-film-cafe/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-vintage-film-cafe-20260706-025730.jpg'),
    "reference-tiramisu/premium-studio-food/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-premium-studio-food-20260706-025730.jpg'),
    "reference-tiramisu/white-product/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-white-product.jpg'),
    "reference-tiramisu/lifestyle-product-scene/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-lifestyle-product-scene.jpg'),
    "reference-tiramisu/packaging-showcase/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-packaging-showcase.jpg'),
    "reference-tiramisu/recipe-flowchart/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-recipe-flowchart.jpg'),
    "reference-tiramisu/step-by-step-infographic/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-step-by-step-infographic.jpg'),
    "reference-tiramisu/hand-drawn-infographic/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-hand-drawn-infographic.jpg'),
    "reference-tiramisu/bento-grid/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-bento-grid.jpg'),
    "reference-tiramisu/product-tvc-storyboard/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-product-tvc-storyboard.jpg'),
    "reference-tiramisu/cinematic-storyboard/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-cinematic-storyboard.jpg'),
    "reference-tiramisu/mixed-style-collage/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-mixed-style-collage.jpg'),
    "reference-tiramisu/brand-poster/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-brand-poster.jpg'),
    "reference-tiramisu/campaign-kv-system/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-campaign-kv-system.jpg'),
    "reference-tiramisu/banner-hero/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-banner-hero.jpg'),
    "reference-tiramisu/editorial-cover/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-editorial-cover.jpg'),
    "reference-tiramisu/vintage-editorial-infographic/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-vintage-editorial-infographic.jpg'),
    "reference-tiramisu/food-map/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-food-map.jpg'),
    "reference-tiramisu/lookbook-grid/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-lookbook-grid.jpg'),
    "reference-tiramisu/banner-grid-2x2/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-banner-grid-2x2.jpg'),
    "reference-tiramisu/retro-icons/1": require('@/assets/images/gpt-image-2/reference-examples/tiramisu-retro-icons.jpg'),
    "reference-dog/healing-watercolor/1": require('@/assets/images/gpt-image-2/reference-examples/dog-healing-watercolor-20260706-025730.jpg'),
    "reference-dog/kawaii-3d-icon/1": require('@/assets/images/gpt-image-2/reference-examples/dog-kawaii-3d-icon-20260706-025730.jpg'),
    "reference-dog/picture-book-scene/1": require('@/assets/images/gpt-image-2/reference-examples/dog-picture-book-scene.jpg'),
    "reference-dog/minimalist-mood-poster/1": require('@/assets/images/gpt-image-2/reference-examples/dog-minimalist-mood-poster.jpg'),
    "reference-dog/cinematic-concept-scene/1": require('@/assets/images/gpt-image-2/reference-examples/dog-cinematic-concept-scene.jpg'),
    "reference-dog/sticker-set/1": require('@/assets/images/gpt-image-2/reference-examples/dog-sticker-set.jpg'),
    "reference-dog/expression-grid/1": require('@/assets/images/gpt-image-2/reference-examples/dog-expression-grid.jpg'),
    "reference-dog/character-sheet/1": require('@/assets/images/gpt-image-2/reference-examples/dog-character-sheet.jpg'),
    "reference-dog/four-panel-comic/1": require('@/assets/images/gpt-image-2/reference-examples/dog-four-panel-comic.jpg'),
    "reference-dog/manga-spread-page/1": require('@/assets/images/gpt-image-2/reference-examples/dog-manga-spread-page.jpg'),
    "reference-dog/anime-key-visual/1": require('@/assets/images/gpt-image-2/reference-examples/dog-anime-key-visual.jpg'),
    "reference-dog/cinematic-storyboard/1": require('@/assets/images/gpt-image-2/reference-examples/dog-cinematic-storyboard.jpg'),
    "reference-dog/mixed-style-collage/1": require('@/assets/images/gpt-image-2/reference-examples/dog-mixed-style-collage.jpg'),
    "reference-dog/mascot-brand-kit/1": require('@/assets/images/gpt-image-2/reference-examples/dog-mascot-brand-kit.jpg'),
    "reference-dog/character-merch-board/1": require('@/assets/images/gpt-image-2/reference-examples/dog-character-merch-board.jpg'),
    "reference-dog/editorial-cover/1": require('@/assets/images/gpt-image-2/reference-examples/dog-editorial-cover.jpg'),
    "reference-dog/brand-poster/1": require('@/assets/images/gpt-image-2/reference-examples/dog-brand-poster.jpg'),
    "reference-dog/campaign-kv-system/1": require('@/assets/images/gpt-image-2/reference-examples/dog-campaign-kv-system.jpg'),
    "reference-dog/banner-hero/1": require('@/assets/images/gpt-image-2/reference-examples/dog-banner-hero.jpg'),
    "reference-dog/retro-icons/1": require('@/assets/images/gpt-image-2/reference-examples/dog-retro-icons.jpg'),
    "reference-dog/bento-memory-card/1": require('@/assets/images/gpt-image-2/reference-examples/dog-bento-memory-card.jpg'),
};
