// Curated GPT Image 2 reference examples.
import type { ImageStylePreviewEntry } from './imageStylePreviewManifest';

export const EXTRA_IMAGE_STYLE_PREVIEW_MANIFEST: Record<string, ImageStylePreviewEntry> = {
    'github-skills/gpt-image-2/1': {
        fileName: 'gpt-image-2-healing-scribble-portrait.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'gpt-image-2/healing-anime-scribble-v3-20260815',
        sourceIndex: 9,
        width: 1448,
        height: 1086,
    },
    'github-skills/photo-illustration-diptych/3': {
        fileName: 'photo-illustration-editorial-echo.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'photo-illustration-diptych/editorial-echo-20260809',
        sourceIndex: 8,
        width: 1448,
        height: 1086,
    },
    'reference-torn-paper-editorial/torn-paper-photo-collage/1': {
        fileName: 'torn-paper-editorial-close-portrait.jpg',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'torn-paper-editorial-reference/01-close-portrait',
        sourceIndex: 45,
        width: 969,
        height: 1615,
    },
    'github-skills/photo-illustration-diptych/2': {
        fileName: 'photo-illustration-diptych-lakeside.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'photo-illustration-diptych/user-reference-lakeside-20260808',
        sourceIndex: 7,
        width: 1448,
        height: 1086,
    },
    'github-skills/photo-illustration-diptych/1': {
        fileName: 'photo-illustration-diptych-user-reference.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'photo-illustration-diptych/user-reference-20260806',
        sourceIndex: 6,
        width: 1448,
        height: 1086,
    },
    'github-skills/scenes-gathered-zine/2': {
        fileName: 'scenes-gathered-zine-sea-user-reference.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'scenes-gathered-zine-v1-3/user-reference-sea',
        sourceIndex: 5,
        width: 1448,
        height: 1086,
    },
    'github-skills/scenes-gathered-zine/1': {
        fileName: 'scenes-gathered-zine-user-reference.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'scenes-gathered-zine-v1-3/user-reference',
        sourceIndex: 4,
        width: 1448,
        height: 1086,
    },
    'github-skills/grade-images/1': {
        fileName: 'grade-images-v0-3-0-user-reference.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'grade-images-v0-3-0/user-reference-natural-standard',
        sourceIndex: 3,
        width: 1448,
        height: 1086,
    },
    'github-skills/scene-distillation-zine/1': {
        fileName: 'scene-distillation-zine-user-reference.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'scene-distillation-zine-v1-3/user-reference',
        sourceIndex: 2,
        width: 1448,
        height: 1086,
    },
    'github-skills/minimal-zine-poster/1': {
        fileName: 'gc-minimal-zine-poster-pause-map.jpg',
        sourceSet: 'github-skill',
        sourceCaseId: 'gc-minimal-zine-poster-v0-1/pause-map',
        sourceIndex: 1,
        width: 1448,
        height: 1086,
    },
    'reference-voxcat/wild-mountain-sketchbook/1': {
        fileName: 'voxcat-wild-mountain-sketchbook.jpg',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'voxcat-reference/01-wild-mountain-sketchbook',
        sourceIndex: 1,
        width: 480,
        height: 640,
    },
    'reference-graphite-cyan/dark-urban-grade/1': {
        fileName: 'graphite-cyan-dark-tone.jpg',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'graphite-cyan-reference/01-dark-urban-grade',
        sourceIndex: 1,
        width: 640,
        height: 853,
    },
    'editing-workflows/vintage-film-editorial/1': {
        fileName: 'vintage-film-editorial.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/vintage-film-editorial',
        sourceIndex: 46,
        width: 1024,
        height: 768,
    },
    'storyboards-and-sequences/product-tvc-storyboard/1': {
        fileName: 'product-tvc-storyboard.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/product-tvc-storyboard',
        sourceIndex: 47,
        width: 1024,
        height: 683,
    },
    'storyboards-and-sequences/cinematic-storyboard/1': {
        fileName: 'cinematic-storyboard.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/cinematic-storyboard',
        sourceIndex: 48,
        width: 1024,
        height: 1024,
    },
    'infographics/vintage-editorial-infographic/1': {
        fileName: 'vintage-editorial-infographic.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/vintage-editorial-infographic',
        sourceIndex: 49,
        width: 683,
        height: 1024,
    },
    'branding-and-packaging/character-merch-board/1': {
        fileName: 'character-merch-board.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/character-merch-board',
        sourceIndex: 50,
        width: 1024,
        height: 683,
    },
    'grids-and-collages/bento-memory-card/1': {
        fileName: 'bento-memory-card.png',
        sourceSet: 'curated-reference-examples',
        sourceCaseId: 'semantic-gallery/bento-memory-card',
        sourceIndex: 51,
        width: 1024,
        height: 1024,
    },
};
