// Curated GPT Image 2 reference examples.
import type { ImageAgentStyleCategory, ImageAgentStylePreset } from './imageStyleTypes';
import { GC_MINIMAL_ZINE_POSTER_LICENSE, GC_MINIMAL_ZINE_POSTER_PROMPT } from './gcMinimalZinePosterPrompt';
import { GRADE_IMAGES_LICENSE_NOTICE, GRADE_IMAGES_PROMPT } from './gradeImagesPrompt';
import { HEALING_SCRIBBLE_SKETCH_LICENSE_NOTICE, HEALING_SCRIBBLE_SKETCH_PROMPT } from './healingScribbleSketchPrompt';
import { PHOTO_ILLUSTRATION_EDITORIAL_ECHO_LICENSE_NOTICE, PHOTO_ILLUSTRATION_EDITORIAL_ECHO_PROMPT } from './photoIllustrationEditorialEchoPrompt';
import { PHOTO_ILLUSTRATION_DIPTYCH_LICENSE_NOTICE, PHOTO_ILLUSTRATION_DIPTYCH_PROMPT } from './photoIllustrationDiptychPrompt';
import { PHOTO_ILLUSTRATION_DIPTYCH_LAKESIDE_PROMPT } from './photoIllustrationDiptychLakesidePrompt';
import { SCENE_DISTILLATION_ZINE_LICENSE, SCENE_DISTILLATION_ZINE_PROMPT } from './sceneDistillationZinePrompt';
import { SCENES_GATHERED_ZINE_LICENSE, SCENES_GATHERED_ZINE_PROMPT } from './scenesGatheredZinePrompt';
import { TORN_PAPER_EDITORIAL_PROMPT } from './tornPaperEditorialPrompt';
import {
    BENTO_MEMORY_CARD_PROMPT,
    CHARACTER_MERCH_BOARD_PROMPT,
    CINEMATIC_STORYBOARD_PROMPT,
    PRODUCT_TVC_STORYBOARD_PROMPT,
    VINTAGE_EDITORIAL_INFOGRAPHIC_PROMPT,
    VINTAGE_FILM_EDITORIAL_PROMPT,
} from './semanticGalleryPrompts';

const RAW_EXTRA_IMAGE_AGENT_STYLE_CATEGORIES: ImageAgentStyleCategory[] = [
    {
        "id": "github-skills",
        "label": "GitHub Skills",
        "labelKey": "agents.imageStyleGithubSkills",
        "accent": "#315D86",
        "count": 9
    },
    {
        "id": "reference-voxcat",
        "label": "山野速写案例",
        "accent": "#7B8F72",
        "count": 1
    },
    {
        "id": "reference-graphite-cyan",
        "label": "石墨青暗调案例",
        "accent": "#466B75",
        "count": 1
    },
    {
        "id": "reference-torn-paper-editorial",
        "label": "撕纸编辑案例",
        "accent": "#B34732",
        "count": 1
    },
];

const RAW_EXTRA_IMAGE_AGENT_STYLE_PRESETS: ImageAgentStylePreset[] = [
    {
        "id": "github-skills/gpt-image-2/1",
        "title": "Healing Scribble Sketch",
        "labelKey": "agents.imageStyleHealingScribbleSketch",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/gpt-image-2/references/avatars-and-profile/style-transfer-selfie.md",
        "templateLabel": "GPT Image 2 · Healing Anime Scribble",
        "templateLabelKey": "agents.imageStyleHealingScribbleSketch",
        "promptHint": "Turn one portrait into a raw healing anime construction sketch with dense searching graphite lines, a calm simplified face, sparse pale color, and broad warm-white paper.\nKeeps identity through face shape, hair, glasses, expression, pose, and one key garment or prop; always text-free.",
        "promptHintKey": "agents.imageStyleHealingScribbleSketchHint",
        "promptContent": HEALING_SCRIBBLE_SKETCH_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/healing-anime-scribble-v3.md",
        "sourceCaseId": "gpt-image-2/healing-anime-scribble-v3-20260815",
        "sourceRepository": "ConardLi/garden-skills",
        "sourceRevision": "aaf9a82f5efd73e87cc0998edc398e75bfc35901",
        "sourceLicenseNotice": HEALING_SCRIBBLE_SKETCH_LICENSE_NOTICE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "continuationSourceMode": "original-upload",
        "responseInstructions": "After sending the image, add a concise 1–3 sentence rationale in the user's current conversation language naming the preserved subject cues, source-derived palette, and balance of searching linework, watercolor, and quiet paper. Do not reveal the full prompt, private source path, or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/photo-illustration-diptych/3",
        "title": "Editorial Echo",
        "labelKey": "agents.imageStylePhotoIllustrationEditorialEcho",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/photo-illustration-diptych/SKILL.md",
        "templateLabel": "Photo–Illustration Diptych · Editorial Echo",
        "templateLabelKey": "agents.imageStylePhotoIllustrationEditorialEcho",
        "promptHint": "Turn one photo into an adaptive portrait or landscape editorial poster with a truthful photo anchor, one isolated watercolor-and-ink echo, and scene-specific title, study label, and short caption composed as crisp real text.",
        "promptHintKey": "agents.imageStylePhotoIllustrationEditorialEchoHint",
        "promptContent": PHOTO_ILLUSTRATION_EDITORIAL_ECHO_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/photo-illustration-editorial-echo-v1.md",
        "sourceCaseId": "photo-illustration-diptych/editorial-echo-20260809",
        "sourceRepository": "wangjs-jacky/happy",
        "sourceRevision": "e8716a0a0c949f8e2b45e1e3d7c8d36ad7bba17c",
        "sourceLicenseNotice": PHOTO_ILLUSTRATION_EDITORIAL_ECHO_LICENSE_NOTICE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "continuationSourceMode": "original-upload",
        "responseInstructions": "After sending the finished poster, add a concise 1–3 sentence rationale in the user's current conversation language naming the selected orientation, the scene-specific copy idea, and the preserved photo-to-illustration correspondence. Do not reveal the full prompt, private source path, temporary motif, HTML path, or detailed parameters unless explicitly requested."
    },
    {
        "id": "reference-torn-paper-editorial/torn-paper-photo-collage/1",
        "title": "撕纸编辑影像拼贴",
        "categoryId": "reference-torn-paper-editorial",
        "categoryLabel": "撕纸编辑案例",
        "categoryAccent": "#B34732",
        "templateRef": "reference-examples/torn-paper-editorial-reference/torn-paper-editorial.md",
        "templateLabel": "Torn Paper Editorial Photo Collage v1",
        "promptHint": "把单张照片重构为 3:5 暖色旧纸编辑拼贴：45%–65% 的彩色主体从大面积不规则撕口中显露，环境化为黑白网点复印层，并用一道钴蓝、朱红或珊瑚色干刷建立结构，可选一行微型打字机字幕。",
        "promptContent": TORN_PAPER_EDITORIAL_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/torn-paper-editorial-v1.md",
        "sourceCaseId": "torn-paper-editorial-reference/01-close-portrait",
        "sourceRepository": "curated-reference-examples",
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "responseInstructions": "After sending the image, add a concise 1-3 sentence rationale in the user's current conversation language that names the preserved subject or scene, torn photographic anchor, monochrome environmental echo, and structural brush color. Do not reveal the full prompt, private source path, or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/photo-illustration-diptych/2",
        "title": "Lakeside Minimal Diptych",
        "labelKey": "agents.imageStylePhotoIllustrationDiptychLakeside",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/photo-illustration-diptych/SKILL.md",
        "templateLabel": "Photo–Illustration Diptych v1 · Lakeside minimal",
        "templateLabelKey": "agents.imageStylePhotoIllustrationDiptychLakeside",
        "promptHint": "Pair one lakeside photo with a radically simplified geometric rendering of the same scene. Preserve the boardwalk curve, dock rhythm, boat position, shoreline, horizon, and mountain profile using source-derived blue, green, coral, and warm-ivory color fields.",
        "promptHintKey": "agents.imageStylePhotoIllustrationDiptychLakesideHint",
        "promptContent": PHOTO_ILLUSTRATION_DIPTYCH_LAKESIDE_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/photo-illustration-diptych-lakeside-v1.md",
        "sourceCaseId": "photo-illustration-diptych/user-reference-lakeside-20260808",
        "sourceRepository": "wangjs-jacky/happy",
        "sourceRevision": "532e49bb711283cbe2738439039298f9cea1ef7b",
        "sourceLicenseNotice": PHOTO_ILLUSTRATION_DIPTYCH_LICENSE_NOTICE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "continuationSourceMode": "original-upload",
        "responseInstructions": "After sending the image, add a concise 1–3 sentence rationale in the user's current conversation language that names the preserved waterside correspondences, source-derived palette, and geometric reduction. Do not reveal the full prompt, private source path, or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/photo-illustration-diptych/1",
        "title": "Photo–Illustration Diptych",
        "labelKey": "agents.imageStylePhotoIllustrationDiptych",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/photo-illustration-diptych/SKILL.md",
        "templateLabel": "Photo–Illustration Diptych v1",
        "templateLabelKey": "agents.imageStylePhotoIllustrationDiptych",
        "promptHint": "Pair one supplied photo with a composition-matched illustration in a calm 3:5 paper poster. Preserve landmark count, horizon, spatial order, and movement while adapting the lower medium to the subject: ink wash, flat editorial, geometric skyline, or Art Deco.",
        "promptHintKey": "agents.imageStylePhotoIllustrationDiptychHint",
        "promptContent": PHOTO_ILLUSTRATION_DIPTYCH_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/photo-illustration-diptych-v1.md",
        "sourceCaseId": "photo-illustration-diptych/user-reference-20260806",
        "sourceRepository": "wangjs-jacky/happy",
        "sourceRevision": "532e49bb711283cbe2738439039298f9cea1ef7b",
        "sourceLicenseNotice": PHOTO_ILLUSTRATION_DIPTYCH_LICENSE_NOTICE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "continuationSourceMode": "original-upload",
        "responseInstructions": "After sending the image, add a concise 1–3 sentence rationale in the user's current conversation language that names the preserved scene correspondences and the selected illustration medium. Do not reveal the full prompt, private source path, or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/scenes-gathered-zine/2",
        "title": "Gathered Scenes Zine · Sea",
        "labelKey": "agents.imageStyleScenesGatheredZineSea",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/scenes-gathered-zine-v1-3/SKILL.md",
        "templateLabel": "Gathered Scenes Zine v1.3 · Sea reference",
        "templateLabelKey": "agents.imageStyleScenesGatheredZineSea",
        "promptHint": "Use the Gathered Scenes compiler for sea, shoreline, railing, ferry, and coastal travel photos: truthful photographic anchor, broad quiet paper fields, fibrous torn boundaries, highly compressed source-derived print marks, one structural hue, and restrained micro-text.",
        "promptHintKey": "agents.imageStyleScenesGatheredZineSeaHint",
        "promptContent": SCENES_GATHERED_ZINE_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/scenes-gathered-zine-v1-3-sea.md",
        "sourceCaseId": "scenes-gathered-zine-v1-3/user-reference-sea",
        "sourceRepository": "Zeejay0/gathered-scenes-zine-skill",
        "sourceRevision": "e764b7fd243d7cc501723b9d325279bf6dd852c2",
        "sourceLicenseNotice": SCENES_GATHERED_ZINE_LICENSE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "responseInstructions": "After sending the image, add a concise 1–3 sentence creative rationale in the user's current conversation language, covering the truthful coastal photo anchor, torn-paper handoff, illustrated negative space, and structural color. Do not reveal the full prompt or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/scenes-gathered-zine/1",
        "title": "Gathered Scenes Zine",
        "labelKey": "agents.imageStyleScenesGatheredZine",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/scenes-gathered-zine-v1-3/SKILL.md",
        "templateLabel": "Gathered Scenes Zine v1.3",
        "templateLabelKey": "agents.imageStyleScenesGatheredZine",
        "promptHint": "Anchor a truthful supplied photo inside a spacious 3:5 tactile paper poster, expand selected source shapes into a highly simplified abstract illustration field, use one high-chroma hue as compositional structure, preserve a visible fibrous torn-paper handoff, and finish with restrained micro-text.",
        "promptHintKey": "agents.imageStyleScenesGatheredZineHint",
        "promptContent": SCENES_GATHERED_ZINE_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/scenes-gathered-zine-v1-3.md",
        "sourceCaseId": "scenes-gathered-zine-v1-3/user-reference",
        "sourceRepository": "Zeejay0/gathered-scenes-zine-skill",
        "sourceRevision": "e764b7fd243d7cc501723b9d325279bf6dd852c2",
        "sourceLicenseNotice": SCENES_GATHERED_ZINE_LICENSE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "responseInstructions": "After sending the image, add a concise 1–3 sentence creative rationale in the user's current conversation language, explaining the source-derived composition, expanded illustration field, and structural role of the high-chroma hue. Do not reveal the full prompt or detailed parameters unless explicitly requested."
    },
    {
        "id": "github-skills/grade-images/1",
        "title": "Deterministic Photo Grade",
        "labelKey": "agents.imageStyleGradeImages",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/grade-images/SKILL.md",
        "templateLabel": "grade-images v0.3.0",
        "templateLabelKey": "agents.imageStyleGradeImages",
        "promptHint": "Deterministically correct, match, or creatively color-grade a JPEG/PNG while strictly preserving geometry, identity, faces, objects, text, and texture. Supports conservative through transformative intensity, recipe-backed previews, quality gates, and explicitly approved source-derived glow.",
        "promptHintKey": "agents.imageStyleGradeImagesHint",
        "promptContent": GRADE_IMAGES_PROMPT,
        "promptPath": "grade-images/recipes/grade-images-v0-3-0.json",
        "sourceCaseId": "grade-images-v0-3-0/user-reference-natural-standard",
        "sourceRepository": "liwushu128-debug/grade-images",
        "sourceRevision": "3e8ecd3b8c2636c7286a052ad147a77549ab9660",
        "sourceLicenseNotice": GRADE_IMAGES_LICENSE_NOTICE,
        "executionKind": "deterministic-grade",
        "inputMode": "image-required",
        "multiInputMode": "batch",
        "supportedInputFormats": ["jpeg", "png"],
        "responseInstructions": "After sending a preview or final image, respond in the user's current conversation language with the grading mode and intensity, key color and tonal treatment, quality-gate result, and any warnings; also deliver the recipe and quality report. Do not expose private source paths or complete command logs."
    },
    {
        "id": "github-skills/scene-distillation-zine/1",
        "title": "Scene Distillation Zine",
        "labelKey": "agents.imageStyleSceneDistillationZine",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/scene-distillation-zine-v1-3/SKILL.md",
        "templateLabel": "Scene Distillation Zine v1.3",
        "templateLabelKey": "agents.imageStyleSceneDistillationZine",
        "promptHint": "Distill a supplied photo into an original portrait 3:5 or landscape 5:3 paper-zine illustration with no retained photographic pixels, expressive paper edges, authorial typography, and one purposeful vivid accent. The exact trigger 单色块模式 enables one contiguous saturated color field.",
        "promptHintKey": "agents.imageStyleSceneDistillationZineHint",
        "promptContent": SCENE_DISTILLATION_ZINE_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/scene-distillation-zine-v1-3.md",
        "sourceCaseId": "scene-distillation-zine-v1-3/user-reference",
        "sourceRepository": "Zeejay0/scene-distillation-zine-v1-3",
        "sourceRevision": "921390baac518c85d60a6d98709f1dd657eec720",
        "sourceLicenseNotice": SCENE_DISTILLATION_ZINE_LICENSE,
        "executionKind": "gpt-image-2",
        "inputMode": "image-required",
        "multiInputMode": "single",
        "responseInstructions": "After sending the image, use the user's current conversation language for concise creative-concept and art-direction notes covering the proposition, core tension, source-derived visual metaphor, and the role of composition, edges, color, and typography. Briefly disclose that the generation service received the final prompt and reference image. Do not reveal the full prompt or paths."
    },
    {
        "id": "github-skills/minimal-zine-poster/1",
        "title": "Minimal Zine Paper Poster",
        "labelKey": "agents.imageStyleMinimalZinePoster",
        "categoryId": "github-skills",
        "categoryLabel": "GitHub Skills",
        "categoryLabelKey": "agents.imageStyleGithubSkills",
        "categoryAccent": "#315D86",
        "templateRef": "skills/gc-minimal-zine-poster-v0-1/SKILL.md",
        "templateLabel": "Minimal Zine Poster v0.1",
        "templateLabelKey": "agents.imageStyleMinimalZinePoster",
        "promptHint": "Turn a theme, short line, object, mood, article idea, or photo into a 3:5 vertical minimal paper poster with aged-paper negative space, a small torn-paper or photo anchor, sparse typewriter text, one vivid accent, and photocopy or scan texture.",
        "promptHintKey": "agents.imageStyleMinimalZinePosterHint",
        "promptContent": GC_MINIMAL_ZINE_POSTER_PROMPT,
        "promptPath": "garden-gpt-image-2/prompt/gc-minimal-zine-poster-v0-1.md",
        "sourceCaseId": "gc-minimal-zine-poster-v0-1/pause-map",
        "sourceRepository": "LiamGvchi/gc-minimal-zine-poster",
        "sourceRevision": "4cb0396ad4e834019f753b37e1c4f415f5e02026",
        "sourceLicenseNotice": GC_MINIMAL_ZINE_POSTER_LICENSE,
        "executionKind": "gpt-image-2",
        "inputMode": "text-or-image",
        "multiInputMode": "batch"
    },
    {
        "id": "reference-voxcat/wild-mountain-sketchbook/1",
        "title": "山野旅行速写手帐",
        "categoryId": "reference-voxcat",
        "categoryLabel": "山野速写案例",
        "categoryAccent": "#7B8F72",
        "templateRef": "reference-examples/voxcat-reference/voxcat-wild-mountain-sketchbook.md",
        "templateLabel": "Wild Mountain Sketchbook",
        "promptHint": "山野旅行手帐风格 prompt：白底留白、黑色钢笔速写、干刷水彩色块、手写批注、箭头和符号，适合山地、草原、冰川、旅人、摄影师与荒野光线主题。",
        "promptContent": "Create an outdoor travel sketchbook field-note illustration inspired by a 12-image mountain reference set. Use warm off-white paper with generous blank margins, loose black ink contour drawing, scratchy construction lines, rough hatch marks, broken dry-brush edges, and broad watercolor-like paint swipes rather than fully filled surfaces. Subject can be a wild mountain ridgeline, high plateau grassland, glacier, winding road above clouds, alpine lake, train passing mountains, ancient stone ruins, small hiker, or photographer chasing light. Palette must stay restrained: glacier blue, pale sky blue, ochre, dry grass gold, olive green, warm beige, slate gray, carbon black, plus one small orange sunlight accent. Add sparse handwritten field-note marks around the scene: arrows, underlines, tiny sun, stars, crosses, compass marks, check marks, palette dots, wind marks, and short handwritten words like wind, wild mountain, golden hour, above the clouds, chase the light, or take time to breathe. Keep the text casual and sparse, not a dense infographic. The main landscape should sit in the center or lower two-thirds and fade into the paper at the edges. Mood: windy, open, free, rugged, contemplative, high-altitude air, rock, grass, snow, and distance. If people appear, keep them small and atmospheric, used for scale rather than portrait detail. Avoid photorealism, smooth vector art, polished anime, glossy 3D, crowded typography, UI labels, realistic map accuracy, corporate poster design, heavy gradients, neon colors, random logos, QR codes, watermarks, social media marks, or dense readable paragraphs.",
        "promptPath": "garden-gpt-image-2/prompt/voxcat-wild-mountain-sketchbook-style.md",
        "sourceCaseId": "voxcat-reference/01-wild-mountain-sketchbook",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-graphite-cyan/dark-urban-grade/1",
        "title": "石墨青暗调",
        "categoryId": "reference-graphite-cyan",
        "categoryLabel": "石墨青暗调案例",
        "categoryAccent": "#466B75",
        "templateRef": "reference-examples/graphite-cyan-reference/graphite-cyan-dark-tone.md",
        "templateLabel": "Graphite Cyan Dark Tone",
        "promptHint": "完整保留原图构图与细节，以低饱和石墨灰青、通透冷蓝暗部和少量暖橙灯光营造雨后都市清冷纪实电影质感。",
        "promptContent": "完整保留原图全部建筑、云层、灯光、构图与原生明暗光影，雨后石墨青专属暗调质感，整体基底为低饱和石墨灰青色，画面光影冷暖分离，大面积暗部自带通透冷蓝底色，不会压成死黑且完整保留云层、玻璃幕墙、墙体纹理细节。建筑钢结构、玻璃呈现沉稳深灰蓝，仅建筑室内外灯光保留柔和暖橙作为色彩点缀，中等偏硬朗对比度，彻底消除画面灰白雾感，叠加细腻哑光胶片颗粒，无刺眼高光、无艳丽霓虹，整体氛围冷静克制，充满都市清冷纪实电影质感，适配阴天、黄昏、雨后各类城市外景拍摄素材。",
        "promptPath": "garden-gpt-image-2/prompt/graphite-cyan-dark-tone.md",
        "sourceCaseId": "graphite-cyan-reference/01-dark-urban-grade",
        "sourceRepository": "curated-reference-examples"
    }
];

export const EXTRA_IMAGE_AGENT_STYLE_CATEGORIES: ImageAgentStyleCategory[] = RAW_EXTRA_IMAGE_AGENT_STYLE_CATEGORIES;

const SEMANTIC_IMAGE_AGENT_STYLE_PRESETS: ImageAgentStylePreset[] = [
    {
        id: 'editing-workflows/vintage-film-editorial/1',
        title: '复古胶片编辑影像',
        categoryId: 'editing-workflows',
        categoryLabel: '图像编辑',
        categoryAccent: '#4A6FA5',
        templateRef: 'semantic-gallery/vintage-film-editorial.md',
        templateLabel: 'Vintage Film Editorial',
        promptHint: '把文字主题或单张图片处理为克制的 35mm 复古胶片编辑影像，保留真实质感、浅景深、暖色电影感与轻微颗粒。',
        promptContent: VINTAGE_FILM_EDITORIAL_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/vintage-film-editorial',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
    {
        id: 'storyboards-and-sequences/product-tvc-storyboard/1',
        title: '产品 TVC 分镜板',
        categoryId: 'storyboards-and-sequences',
        categoryLabel: '叙事序列',
        categoryAccent: '#A23E48',
        templateRef: 'semantic-gallery/product-tvc-storyboard.md',
        templateLabel: 'Product TVC Storyboard',
        promptHint: '把一个产品或主题编排成 3×2 商业短片分镜，统一主体、光线、镜头语言与六步叙事。',
        promptContent: PRODUCT_TVC_STORYBOARD_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/product-tvc-storyboard',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
    {
        id: 'storyboards-and-sequences/cinematic-storyboard/1',
        title: '电影分镜板',
        categoryId: 'storyboards-and-sequences',
        categoryLabel: '叙事序列',
        categoryAccent: '#A23E48',
        templateRef: 'semantic-gallery/cinematic-storyboard.md',
        templateLabel: 'Cinematic Storyboard',
        promptHint: '把主题或图片发展成连续一致的 3×3 电影分镜，覆盖建立、细节、转折与收束镜头。',
        promptContent: CINEMATIC_STORYBOARD_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/cinematic-storyboard',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
    {
        id: 'infographics/vintage-editorial-infographic/1',
        title: '复古编辑信息图',
        categoryId: 'infographics',
        categoryLabel: '信息图',
        categoryAccent: '#D4665A',
        templateRef: 'semantic-gallery/vintage-editorial-infographic.md',
        templateLabel: 'Vintage Editorial Infographic',
        promptHint: '用暖白纸、档案色油墨、细线与稀疏排版，把主题编译成纵向复古编辑信息图，不虚构数据。',
        promptContent: VINTAGE_EDITORIAL_INFOGRAPHIC_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/vintage-editorial-infographic',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
    {
        id: 'branding-and-packaging/character-merch-board/1',
        title: '角色周边商品板',
        categoryId: 'branding-and-packaging',
        categoryLabel: '品牌包装',
        categoryAccent: '#B8860B',
        templateRef: 'semantic-gallery/character-merch-board.md',
        templateLabel: 'Character Merchandise Board',
        promptHint: '把单一角色稳定地应用到玩偶、徽章、贴纸、杯子、帆布袋、壁纸、明信片和挂件的编辑商品板。',
        promptContent: CHARACTER_MERCH_BOARD_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/character-merch-board',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
    {
        id: 'grids-and-collages/bento-memory-card/1',
        title: 'Bento 记忆卡',
        categoryId: 'grids-and-collages',
        categoryLabel: '网格拼贴',
        categoryAccent: '#2E7D8B',
        templateRef: 'semantic-gallery/bento-memory-card.md',
        templateLabel: 'Bento Memory Card',
        promptHint: '把一个主题或一张图片整理为 7–8 模块的温暖 Bento 记忆卡，突出主视觉、细节、色板、材质与小型记录。',
        promptContent: BENTO_MEMORY_CARD_PROMPT,
        promptPath: 'packages/happy-app/sources/components/agents/semanticGalleryPrompts.ts',
        sourceCaseId: 'semantic-gallery/bento-memory-card',
        sourceRepository: 'wangjs-jacky/happy',
        executionKind: 'gpt-image-2',
        inputMode: 'text-or-image',
        multiInputMode: 'single',
    },
];

export const EXTRA_IMAGE_AGENT_STYLE_PRESETS: ImageAgentStylePreset[] = [
    ...RAW_EXTRA_IMAGE_AGENT_STYLE_PRESETS,
    ...SEMANTIC_IMAGE_AGENT_STYLE_PRESETS,
];

export const EXTRA_LEGACY_IMAGE_STYLE_ID_ALIASES: Record<string, string> = {
    'vintage-film': 'editing-workflows/vintage-film-editorial/1',
    'tvc-storyboard': 'storyboards-and-sequences/product-tvc-storyboard/1',
    'cinematic-storyboard': 'storyboards-and-sequences/cinematic-storyboard/1',
    'vintage-editorial': 'infographics/vintage-editorial-infographic/1',
    'reference-tiramisu/vintage-film-cafe/1': 'editing-workflows/vintage-film-editorial/1',
    'reference-tiramisu/premium-studio-food/1': 'product-visuals/premium-studio-product/1',
    'reference-tiramisu/white-product/1': 'product-visuals/white-background-product/1',
    'reference-tiramisu/lifestyle-product-scene/1': 'product-visuals/lifestyle-product-scene/1',
    'reference-tiramisu/packaging-showcase/1': 'product-visuals/packaging-showcase/2',
    'reference-tiramisu/recipe-flowchart/1': 'storyboards-and-sequences/recipe-process-flowchart/2',
    'reference-tiramisu/step-by-step-infographic/1': 'infographics/step-by-step-infographic/2',
    'reference-tiramisu/hand-drawn-infographic/1': 'infographics/hand-drawn-infographic/1',
    'reference-tiramisu/bento-grid/1': 'infographics/bento-grid-infographic/1',
    'reference-tiramisu/product-tvc-storyboard/1': 'storyboards-and-sequences/product-tvc-storyboard/1',
    'reference-tiramisu/cinematic-storyboard/1': 'storyboards-and-sequences/cinematic-storyboard/1',
    'reference-tiramisu/mixed-style-collage/1': 'grids-and-collages/mixed-style-multi-panel/1',
    'reference-tiramisu/brand-poster/1': 'poster-and-campaigns/brand-poster/1',
    'reference-tiramisu/campaign-kv-system/1': 'poster-and-campaigns/campaign-kv/1',
    'reference-tiramisu/banner-hero/1': 'poster-and-campaigns/banner-hero/1',
    'reference-tiramisu/editorial-cover/1': 'poster-and-campaigns/editorial-cover/2',
    'reference-tiramisu/vintage-editorial-infographic/1': 'infographics/vintage-editorial-infographic/1',
    'reference-tiramisu/food-map/1': 'maps/food-map/1',
    'reference-tiramisu/lookbook-grid/1': 'grids-and-collages/lookbook-grid/1',
    'reference-tiramisu/banner-grid-2x2/1': 'grids-and-collages/banner-grid-2x2/2',
    'reference-tiramisu/retro-icons/1': 'assets-and-props/retro-skeuomorphic-icons/2',
    'reference-dog/healing-watercolor/1': 'scenes-and-illustrations/healing-scene/2',
    'reference-dog/kawaii-3d-icon/1': 'avatars-and-profile/themed-3d-icon/1',
    'reference-dog/picture-book-scene/1': 'scenes-and-illustrations/picture-book-scene/2',
    'reference-dog/minimalist-mood-poster/1': 'scenes-and-illustrations/minimalist-mood-scene/2',
    'reference-dog/cinematic-concept-scene/1': 'scenes-and-illustrations/concept-scene/1',
    'reference-dog/sticker-set/1': 'avatars-and-profile/sticker-set/2',
    'reference-dog/expression-grid/1': 'avatars-and-profile/character-grid-portrait/2',
    'reference-dog/character-sheet/1': 'portraits-and-characters/character-sheet/1',
    'reference-dog/four-panel-comic/1': 'storyboards-and-sequences/four-panel-comic/1',
    'reference-dog/manga-spread-page/1': 'storyboards-and-sequences/manga-spread-page/2',
    'reference-dog/anime-key-visual/1': 'storyboards-and-sequences/anime-key-visual/2',
    'reference-dog/cinematic-storyboard/1': 'storyboards-and-sequences/cinematic-storyboard/1',
    'reference-dog/mixed-style-collage/1': 'grids-and-collages/mixed-style-multi-panel/1',
    'reference-dog/mascot-brand-kit/1': 'branding-and-packaging/mascot-brand-kit/1',
    'reference-dog/character-merch-board/1': 'branding-and-packaging/character-merch-board/1',
    'reference-dog/editorial-cover/1': 'poster-and-campaigns/editorial-cover/2',
    'reference-dog/brand-poster/1': 'poster-and-campaigns/brand-poster/1',
    'reference-dog/campaign-kv-system/1': 'poster-and-campaigns/campaign-kv/1',
    'reference-dog/banner-hero/1': 'poster-and-campaigns/banner-hero/1',
    'reference-dog/retro-icons/1': 'assets-and-props/retro-skeuomorphic-icons/2',
    'reference-dog/bento-memory-card/1': 'grids-and-collages/bento-memory-card/1',
};
