// Curated GPT Image 2 reference examples.
import type { ImageAgentStyleCategory, ImageAgentStylePreset } from './imageStyleTypes';

export const EXTRA_IMAGE_AGENT_STYLE_CATEGORIES: ImageAgentStyleCategory[] = [
    {
        "id": "reference-tiramisu",
        "label": "提拉米苏案例",
        "accent": "#A66A3F",
        "count": 21
    },
    {
        "id": "reference-dog",
        "label": "小狗案例",
        "accent": "#6E8B5B",
        "count": 21
    }
];

export const EXTRA_IMAGE_AGENT_STYLE_PRESETS: ImageAgentStylePreset[] = [
    {
        "id": "reference-tiramisu/vintage-film-cafe/1",
        "title": "复古胶片咖啡馆",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-vintage-film-cafe-20260706-025730.md",
        "templateLabel": "Vintage Film Cafe",
        "promptHint": "提拉米苏参考照片风格 prompt：复古胶片咖啡馆。",
        "promptContent": "Transform the source photo into a nostalgic 35mm film café editorial image. Preserve the main scene from the input: a rectangular tiramisu dessert on a white oval plate on a dark wooden table, cocoa powder on top, cream layers, laptop edge on the left, napkin and fork in the background, warm café interior mood. Style: vintage film photography, gentle halation, Kodak-like warm tones, realistic dessert texture, shallow depth of field, subtle grain, cinematic crop, cozy evening café atmosphere. Remove or soften any timestamp/watermark if present. No added readable text, no brand logos, no extra hands, no extra food items.",
        "promptPath": "garden-gpt-image-2/prompt/tiramisu-vintage-film-cafe-20260706-025730.md",
        "sourceCaseId": "tiramisu-reference/01-vintage-film-cafe",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/premium-studio-food/1",
        "title": "高级影棚甜点摄影",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-premium-studio-food-20260706-025730.md",
        "templateLabel": "Premium Studio Food",
        "promptHint": "提拉米苏参考照片风格 prompt：高级影棚甜点摄影。",
        "promptContent": "Recompose the source tiramisu photo as a premium studio food-advertising product visual. Preserve the dessert identity from the input: rectangular tiramisu with cocoa powder top, visible cream layers, served on a white oval plate. Remove laptop, timestamp, clutter, fork, napkin, and background distractions. Place the tiramisu as the only hero subject on a refined dark walnut tabletop, subtle cocoa dust around the plate, warm golden 45-degree key light, weak fill light, shallow depth of field, magazine-level commercial food photography, rich cream texture, appetizing but restrained. Color palette: dark walnut, ivory cream, cocoa brown, warm gold. No text, no logo, no watermark, no people, no extra dishes.",
        "promptPath": "garden-gpt-image-2/prompt/tiramisu-premium-studio-food-20260706-025730.md",
        "sourceCaseId": "tiramisu-reference/02-premium-studio-food",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/white-product/1",
        "title": "白底电商主图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-white-product.md",
        "templateLabel": "White Product",
        "promptHint": "提拉米苏参考照片风格 prompt：白底电商主图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a clean white-background ecommerce product image of the tiramisu from the reference. Isolate the layered cocoa-dusted tiramisu on its white plate, remove laptop and clutter, pure white background, soft realistic shadow, commercial food photography, no text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-white-product.md",
        "sourceCaseId": "tiramisu-reference/03-white-product",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/lifestyle-product-scene/1",
        "title": "生活方式产品场景",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-lifestyle-product-scene.md",
        "templateLabel": "Lifestyle Product Scene",
        "promptHint": "提拉米苏参考照片风格 prompt：生活方式产品场景。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a lifestyle product scene based on the cafe tiramisu photo. Keep the layered tiramisu and white plate as hero, on a warm wooden cafe table with soft evening light, subtle laptop edge and napkin as background props, remove timestamp, realistic editorial food photography, no text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-lifestyle-product-scene.md",
        "sourceCaseId": "tiramisu-reference/04-lifestyle-product-scene",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/packaging-showcase/1",
        "title": "包装展示图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-packaging-showcase.md",
        "templateLabel": "Packaging Showcase",
        "promptHint": "提拉米苏参考照片风格 prompt：包装展示图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a premium packaging showcase for a tiramisu dessert gift box inspired by the reference. Include an opened elegant cream-colored box, the tiramisu slice on a plate, small dessert card, fork, cocoa powder accents, warm cafe palette, refined commercial photography, placeholder logo only, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-packaging-showcase.md",
        "sourceCaseId": "tiramisu-reference/05-packaging-showcase",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/recipe-flowchart/1",
        "title": "食谱流程图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-recipe-flowchart.md",
        "templateLabel": "Recipe Flowchart",
        "promptHint": "提拉米苏参考照片风格 prompt：食谱流程图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate an illustrated recipe process flowchart for making tiramisu inspired by the reference dessert. Six clear steps with small warm illustrations: espresso soak, mascarpone cream, layer biscuits, add cream, dust cocoa, chill and serve. Final dish resembles the reference. Hand-drawn food magazine style, numbered icons, minimal simple labels only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-recipe-flowchart.md",
        "sourceCaseId": "tiramisu-reference/06-recipe-flowchart",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/step-by-step-infographic/1",
        "title": "步骤教程信息图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-step-by-step-infographic.md",
        "templateLabel": "Step By Step Infographic",
        "promptHint": "提拉米苏参考照片风格 prompt：步骤教程信息图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a warm step-by-step infographic for tiramisu. Vertical zigzag layout, 5 illustrated steps connected with hand-drawn arrows, final large plated tiramisu based on the reference, cream paper background, espresso brown and mascarpone cream palette, visual-heavy, no dense text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-step-by-step-infographic.md",
        "sourceCaseId": "tiramisu-reference/07-step-by-step-infographic",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/hand-drawn-infographic/1",
        "title": "手绘食品信息图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-hand-drawn-infographic.md",
        "templateLabel": "Hand Drawn Infographic",
        "promptHint": "提拉米苏参考照片风格 prompt：手绘食品信息图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a hand-drawn bullet-journal style food infographic about the tiramisu in the reference. Warm cream paper, wobbly ink lines, small doodles of cocoa, fork, espresso, mascarpone, biscuit layers, one central dessert illustration. Use short placeholder handwritten labels, generous whitespace, cozy cafe feeling.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-hand-drawn-infographic.md",
        "sourceCaseId": "tiramisu-reference/08-hand-drawn-infographic",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/bento-grid/1",
        "title": "Bento Grid 食物概览",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-bento-grid.md",
        "templateLabel": "Bento Grid",
        "promptHint": "提拉米苏参考照片风格 prompt：Bento Grid 食物概览。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a bento grid food overview poster for the tiramisu cafe moment. 8 rounded modules: large hero dessert photo-style image, layer close-up, cocoa powder detail, fork detail, cafe table texture, flavor notes, warm color palette, tiny mood block. Modern editorial bento layout, minimal placeholder labels only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-bento-grid.md",
        "sourceCaseId": "tiramisu-reference/09-bento-grid",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/product-tvc-storyboard/1",
        "title": "产品 TVC 分镜",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-product-tvc-storyboard.md",
        "templateLabel": "Product Tvc Storyboard",
        "promptHint": "提拉米苏参考照片风格 prompt：产品 TVC 分镜。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 3x3 premium product TVC storyboard for the tiramisu dessert. Nine realistic ad still panels: cafe establishing shot, hero plate reveal, cocoa dust close-up, cream layer macro, fork approaching, bite lifted, coffee pairing, warm table ambience, final hero packshot. Consistent dessert shape and warm cinematic lighting, thin panel dividers, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-product-tvc-storyboard.md",
        "sourceCaseId": "tiramisu-reference/10-product-tvc-storyboard",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/cinematic-storyboard/1",
        "title": "电影短片分镜",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-cinematic-storyboard.md",
        "templateLabel": "Cinematic Storyboard",
        "promptHint": "提拉米苏参考照片风格 prompt：电影短片分镜。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 3x3 cinematic short-film storyboard around the cafe tiramisu and a quiet laptop work evening. Panels: laptop glow, dessert arrives, fork on napkin, cocoa texture close-up, cream layer macro, first bite, table reflection, warm cafe background, final calm wide shot. Film still style, no dialogue text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-cinematic-storyboard.md",
        "sourceCaseId": "tiramisu-reference/11-cinematic-storyboard",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/mixed-style-collage/1",
        "title": "多风格拼贴",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-mixed-style-collage.md",
        "templateLabel": "Mixed Style Collage",
        "promptHint": "提拉米苏参考照片风格 prompt：多风格拼贴。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a five-panel mixed-style collage of the same tiramisu dessert. Center photoreal food editorial shot; four corners modern anime cafe illustration, classical oil painting still life, 16-bit pixel dessert, cute 3D clay food icon. Unified warm paper background and thin dividers, simple style tags optional.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-mixed-style-collage.md",
        "sourceCaseId": "tiramisu-reference/12-mixed-style-collage",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/brand-poster/1",
        "title": "甜点品牌主海报",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-brand-poster.md",
        "templateLabel": "Brand Poster",
        "promptHint": "提拉米苏参考照片风格 prompt：甜点品牌主海报。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a premium dessert brand poster based on the tiramisu reference. Hero plated tiramisu with cocoa dust and cream layers, warm dark wooden table, refined studio-cafe lighting, ample blank poster space, small placeholder logo mark, elegant layout, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-brand-poster.md",
        "sourceCaseId": "tiramisu-reference/13-brand-poster",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/campaign-kv-system/1",
        "title": "Campaign KV 系统",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-campaign-kv-system.md",
        "templateLabel": "Campaign Kv System",
        "promptHint": "提拉米苏参考照片风格 prompt：Campaign KV 系统。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a campaign key visual system board for a cozy cafe dessert campaign. Use the tiramisu as the anchor visual. Show one large main visual plus three small derivative previews for square social post, vertical story, horizontal banner. Warm coffee, cream, cocoa palette, placeholder text blocks only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-campaign-kv-system.md",
        "sourceCaseId": "tiramisu-reference/14-campaign-kv-system",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/banner-hero/1",
        "title": "Web Hero 横幅",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-banner-hero.md",
        "templateLabel": "Banner Hero",
        "promptHint": "提拉米苏参考照片风格 prompt：Web Hero 横幅。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a wide web hero banner for a dessert cafe. Right side: the tiramisu from the reference as a sharp delicious hero on the white plate. Left side: clean negative space with headline and button placeholders. Warm cafe table, soft highlights, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-banner-hero.md",
        "sourceCaseId": "tiramisu-reference/15-banner-hero",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/editorial-cover/1",
        "title": "食物杂志封面",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-editorial-cover.md",
        "templateLabel": "Editorial Cover",
        "promptHint": "提拉米苏参考照片风格 prompt：食物杂志封面。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a food magazine editorial cover style image. Main visual: the tiramisu from the reference, cocoa powder and cream layers prominent, fork and napkin as refined props. Add masthead-like blank typography blocks and small barcode placeholder, warm cafe editorial photography, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-editorial-cover.md",
        "sourceCaseId": "tiramisu-reference/16-editorial-cover",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/vintage-editorial-infographic/1",
        "title": "复古编辑信息图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-vintage-editorial-infographic.md",
        "templateLabel": "Vintage Editorial Infographic",
        "promptHint": "提拉米苏参考照片风格 prompt：复古编辑信息图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a vintage editorial food infographic poster about tiramisu. Aged cream paper, dark espresso ink, old cafe archive style, central engraved-style tiramisu illustration based on the reference, small diagrams of layers, espresso, cocoa, mascarpone, and a simple timeline-like strip. Decorative labels can be short placeholders only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-vintage-editorial-infographic.md",
        "sourceCaseId": "tiramisu-reference/17-vintage-editorial-infographic",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/food-map/1",
        "title": "咖啡馆甜点地图",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-food-map.md",
        "templateLabel": "Food Map",
        "promptHint": "提拉米苏参考照片风格 prompt：咖啡馆甜点地图。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a hand-drawn cafe dessert map centered on the tiramisu from the reference, as if mapping a cozy cafe tabletop. Include illustrated islands for espresso, fork, napkin, laptop corner, wooden table, cocoa dust, cream layer, and the hero tiramisu plate in the center. Warm watercolor map style, tiny icon legend, no dense text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-food-map.md",
        "sourceCaseId": "tiramisu-reference/18-food-map",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/lookbook-grid/1",
        "title": "咖啡甜点 Lookbook",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-lookbook-grid.md",
        "templateLabel": "Lookbook Grid",
        "promptHint": "提拉米苏参考照片风格 prompt：咖啡甜点 Lookbook。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 7-panel cafe dessert lookbook grid using the reference tiramisu as the hero dessert. Each panel shows a different serving mood: classic plate, coffee pairing, close-up layers, fork bite, table scene, gift box idea, evening cafe mood. Unified warm editorial photography, small day labels optional, no dense text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-lookbook-grid.md",
        "sourceCaseId": "tiramisu-reference/19-lookbook-grid",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/banner-grid-2x2/1",
        "title": "2×2 Banner 套装",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-banner-grid-2x2.md",
        "templateLabel": "Banner Grid 2x2",
        "promptHint": "提拉米苏参考照片风格 prompt：2×2 Banner 套装。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 2x2 set of dessert cafe promotional banners using the tiramisu reference. Four panels share one warm cream, espresso, cocoa palette: new dessert, coffee pairing, takeaway gift, evening cafe mood. Each panel can be cropped independently, consistent layout, CTA placeholder shapes only, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-banner-grid-2x2.md",
        "sourceCaseId": "tiramisu-reference/20-banner-grid-2x2",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-tiramisu/retro-icons/1",
        "title": "复古拟物图标集",
        "categoryId": "reference-tiramisu",
        "categoryLabel": "提拉米苏案例",
        "categoryAccent": "#A66A3F",
        "templateRef": "reference-examples/tiramisu-reference/tiramisu-retro-icons.md",
        "templateLabel": "Retro Icons",
        "promptHint": "提拉米苏参考照片风格 prompt：复古拟物图标集。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 4x3 retro skeuomorphic icon set inspired by the tiramisu cafe photo. Icons include tiramisu slice, cocoa dust, mascarpone cream, espresso cup, fork, napkin, white plate, wooden table, laptop corner, takeout box, coffee bean, tiny star. Rounded square bases, glossy soft 3D material, consistent lighting, labels optional.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/tiramisu-retro-icons.md",
        "sourceCaseId": "tiramisu-reference/21-retro-icons",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/healing-watercolor/1",
        "title": "治愈水彩日常插画",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-healing-watercolor-20260706-025730.md",
        "templateLabel": "Healing Watercolor",
        "promptHint": "小狗参考照片风格 prompt：治愈水彩日常插画。",
        "promptContent": "Transform the source photo into a warm healing daily-scene illustration. Use the input image as the visual reference and preserve the main subject: a small cream-colored curly dog resting its head on a black leather sofa, sleepy half-lidded eyes, black nose, relaxed pose, close-up horizontal composition, light brick wall behind it. Style: hand-painted soft anime illustration plus watercolor softness, gentle paper grain, low-saturation cream, warm beige, muted black, calm natural side light, cozy quiet mood. Keep the dog recognizable and preserve the resting pose. No text, no logo, no watermark, no extra people, no added animals.",
        "promptPath": "garden-gpt-image-2/prompt/dog-healing-watercolor-20260706-025730.md",
        "sourceCaseId": "dog-reference/01-healing-watercolor",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/kawaii-3d-icon/1",
        "title": "可爱 3D 图标",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-kawaii-3d-icon-20260706-025730.md",
        "templateLabel": "Kawaii 3d Icon",
        "promptHint": "小狗参考照片风格 prompt：可爱 3D 图标。",
        "promptContent": "Create a 1:1 rounded-square Kawaii 3D character icon based on the source dog. Preserve the dog identity cues from the input image: cream curly fluffy fur, small black nose, sleepy gentle eyes, soft round muzzle, relaxed sleepy personality. Reinterpret it as a cute 3D avatar bust, head resting on a tiny simplified black cushion, centered with 10% safe margin. Style: polished Kawaii 3D, soft toon shading, warm cream and caramel palette, subtle rim light, clean pale cream background with very faint glow. Keep details simple and icon-ready. No readable text, no logo, no watermark, no harsh realism, no busy background.",
        "promptPath": "garden-gpt-image-2/prompt/dog-kawaii-3d-icon-20260706-025730.md",
        "sourceCaseId": "dog-reference/02-kawaii-3d-icon",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/picture-book-scene/1",
        "title": "绘本场景",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-picture-book-scene.md",
        "templateLabel": "Picture Book Scene",
        "promptHint": "小狗参考照片风格 prompt：绘本场景。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a warm picture-book scene based on the sleepy cream curly dog resting on the black leather sofa. Soft watercolor and colored pencil texture, gentle brick wall background, cozy quiet cafe afternoon, childlike but refined composition, rounded shapes, visible paper grain, no text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-picture-book-scene.md",
        "sourceCaseId": "dog-reference/03-picture-book-scene",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/minimalist-mood-poster/1",
        "title": "极简情绪海报",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-minimalist-mood-poster.md",
        "templateLabel": "Minimalist Mood Poster",
        "promptHint": "小狗参考照片风格 prompt：极简情绪海报。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nTurn the photo into a minimalist mood poster: the same small cream curly dog sleeping on a broad black sofa shape, lots of warm off-white negative space, subtle shadow, calm gallery-poster composition, restrained palette of ivory, black, warm beige, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-minimalist-mood-poster.md",
        "sourceCaseId": "dog-reference/04-minimalist-mood-poster",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/cinematic-concept-scene/1",
        "title": "电影概念场景",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-cinematic-concept-scene.md",
        "templateLabel": "Cinematic Concept Scene",
        "promptHint": "小狗参考照片风格 prompt：电影概念场景。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate cinematic concept art from the reference: a tiny sleepy cream curly dog as the quiet guardian of a late-night cafe, resting on the black leather sofa, warm brick wall, dramatic soft rim light, volumetric dust, filmic color grading, high-detail environment, no text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-cinematic-concept-scene.md",
        "sourceCaseId": "dog-reference/05-cinematic-concept-scene",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/sticker-set/1",
        "title": "贴纸套装",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-sticker-set.md",
        "templateLabel": "Sticker Set",
        "promptHint": "小狗参考照片风格 prompt：贴纸套装。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nDesign a 3x3 sticker sheet of the same cream curly dog character from the photo. Nine expressive poses: sleepy, yawning, happy, curious, paws up, curled up, peeking, tiny wave, proud sit. White sticker outlines, soft shadows, consistent character design, cute but not childish, no text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-sticker-set.md",
        "sourceCaseId": "dog-reference/06-sticker-set",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/expression-grid/1",
        "title": "表情九宫格",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-expression-grid.md",
        "templateLabel": "Expression Grid",
        "promptHint": "小狗参考照片风格 prompt：表情九宫格。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a clean 3x3 character expression grid for the same cream curly dog from the photo. Each square shows the same dog face or upper body with a different expression: sleepy, relaxed, surprised, happy, shy, curious, hungry, confused, peaceful. Studio-white grid background, consistent lighting and face shape, simple tiny labels are optional.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-expression-grid.md",
        "sourceCaseId": "dog-reference/07-expression-grid",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/character-sheet/1",
        "title": "角色设定页",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-character-sheet.md",
        "templateLabel": "Character Sheet",
        "promptHint": "小狗参考照片风格 prompt：角色设定页。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate an animation studio character sheet for the same small cream curly dog. Include front, side, back views; a small expression row; color swatches for cream fur, black nose, warm beige shadows, black sofa accent. Clean beige grid paper background, subtle annotation lines, consistent proportions, minimal placeholder labels only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-character-sheet.md",
        "sourceCaseId": "dog-reference/08-character-sheet",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/four-panel-comic/1",
        "title": "四格漫画",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-four-panel-comic.md",
        "templateLabel": "Four Panel Comic",
        "promptHint": "小狗参考照片风格 prompt：四格漫画。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nMake a four-panel comic based on the sleepy dog in the cafe: 1 the dog tries to watch the room, 2 eyes grow heavy, 3 chin slowly sinks onto the black sofa, 4 fully asleep and peaceful. Cozy comic style, clear panel borders, expressive body language, minimal or no speech bubbles, no dense text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-four-panel-comic.md",
        "sourceCaseId": "dog-reference/09-four-panel-comic",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/manga-spread-page/1",
        "title": "漫画跨页",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-manga-spread-page.md",
        "templateLabel": "Manga Spread Page",
        "promptHint": "小狗参考照片风格 prompt：漫画跨页。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a single-page manga-style multi-panel spread about the same sleepy cream curly dog in the cafe. Six irregular panels: close-up nose, sleepy eyes, paw on black leather, brick wall cafe ambience, slow yawn, final large peaceful sleep panel. Black-and-white ink with warm beige spot tone, screen tones, no readable dialogue.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-manga-spread-page.md",
        "sourceCaseId": "dog-reference/10-manga-spread-page",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/anime-key-visual/1",
        "title": "动漫主视觉",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-anime-key-visual.md",
        "templateLabel": "Anime Key Visual",
        "promptHint": "小狗参考照片风格 prompt：动漫主视觉。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate an anime key visual poster with the same fluffy cream dog as the main character, lying on the black leather sofa in a cozy cafe. Modern anime painting, cinematic warm light, gentle magical-realism atmosphere, title-safe empty area at top, no readable title, highly finished IP poster feeling.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-anime-key-visual.md",
        "sourceCaseId": "dog-reference/11-anime-key-visual",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/cinematic-storyboard/1",
        "title": "电影分镜板",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-cinematic-storyboard.md",
        "templateLabel": "Cinematic Storyboard",
        "promptHint": "小狗参考照片风格 prompt：电影分镜板。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 3x3 cinematic storyboard contact sheet for a quiet short film called a sleepy cafe afternoon. All panels feature the same cream curly dog and the black leather sofa: establishing cafe shot, dog close-up, paw detail, light shifting on brick wall, tiny yawn, listening to room ambience, lowering head, close-up eyes, final peaceful wide shot. Film still style, consistent warm color grading, thin dividers, no dialogue text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-cinematic-storyboard.md",
        "sourceCaseId": "dog-reference/12-cinematic-storyboard",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/mixed-style-collage/1",
        "title": "多风格拼贴",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-mixed-style-collage.md",
        "templateLabel": "Mixed Style Collage",
        "promptHint": "小狗参考照片风格 prompt：多风格拼贴。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a five-panel mixed-style collage of the same cream curly dog on the black sofa. Center: refined photoreal editorial image. Corners: modern anime, classical oil painting, 16-bit pixel art, cute 3D clay icon. Use a unified warm paper background and thin white dividers, simple tiny style tags only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-mixed-style-collage.md",
        "sourceCaseId": "dog-reference/13-mixed-style-collage",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/mascot-brand-kit/1",
        "title": "吉祥物品牌套装",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-mascot-brand-kit.md",
        "templateLabel": "Mascot Brand Kit",
        "promptHint": "小狗参考照片风格 prompt：吉祥物品牌套装。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nDesign a mascot brand kit for a gentle sleepy cafe dog based on the reference. Multi-section board: hero mascot, front/side/back mini views, six expressions, four simple application mockups such as sticker, mug, cafe sign, phone wallpaper. Warm cream and black palette, clean rounded layout, no real brand logo, placeholder text only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-mascot-brand-kit.md",
        "sourceCaseId": "dog-reference/14-mascot-brand-kit",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/character-merch-board/1",
        "title": "角色周边商品板",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-character-merch-board.md",
        "templateLabel": "Character Merch Board",
        "promptHint": "小狗参考照片风格 prompt：角色周边商品板。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a character merchandise board based on the same sleepy cream dog. Include plush toy, enamel pin, sticker pack, mug, tote bag, phone wallpaper, small postcard, acrylic keychain. Clean editorial catalog layout, cozy cafe color palette, consistent dog illustration across all products, no readable brand text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-character-merch-board.md",
        "sourceCaseId": "dog-reference/15-character-merch-board",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/editorial-cover/1",
        "title": "编辑杂志封面",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-editorial-cover.md",
        "templateLabel": "Editorial Cover",
        "promptHint": "小狗参考照片风格 prompt：编辑杂志封面。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nTurn the dog photo into an editorial magazine cover style image. Main visual: the same cream curly dog resting on a black leather sofa, close crop, refined natural light, quiet lifestyle magazine aesthetic. Include masthead-like blank typography blocks and a barcode-style placeholder, but no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-editorial-cover.md",
        "sourceCaseId": "dog-reference/16-editorial-cover",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/brand-poster/1",
        "title": "品牌主海报",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-brand-poster.md",
        "templateLabel": "Brand Poster",
        "promptHint": "小狗参考照片风格 prompt：品牌主海报。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a clean brand poster style visual for a cozy pet cafe moment. Main visual is the same sleepy cream curly dog on the black sofa, large visual anchor, warm brick wall, premium but gentle lighting, ample blank area for a short slogan, placeholder logo mark only, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-brand-poster.md",
        "sourceCaseId": "dog-reference/17-brand-poster",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/campaign-kv-system/1",
        "title": "Campaign KV 系统",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-campaign-kv-system.md",
        "templateLabel": "Campaign Kv System",
        "promptHint": "小狗参考照片风格 prompt：Campaign KV 系统。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a campaign key visual system board for a cozy pet-cafe seasonal campaign using the same dog as the anchor. Show one large main visual plus three smaller derivative layout previews for square, vertical story, and horizontal banner. Warm cream, black leather, soft brick palette. Placeholder text blocks only.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-campaign-kv-system.md",
        "sourceCaseId": "dog-reference/18-campaign-kv-system",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/banner-hero/1",
        "title": "Web Hero 横幅",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-banner-hero.md",
        "templateLabel": "Banner Hero",
        "promptHint": "小狗参考照片风格 prompt：Web Hero 横幅。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a wide web hero banner visual based on the dog photo. Right side: same sleepy cream curly dog on black sofa. Left side: generous clean negative space for headline and button placeholders. Warm cafe background, calm premium pet-lifestyle tone, no readable text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-banner-hero.md",
        "sourceCaseId": "dog-reference/19-banner-hero",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/retro-icons/1",
        "title": "复古拟物图标集",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-retro-icons.md",
        "templateLabel": "Retro Icons",
        "promptHint": "小狗参考照片风格 prompt：复古拟物图标集。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a 4x3 retro skeuomorphic icon set inspired by the dog photo. Icons include sleepy dog face, black sofa cushion, paw, nose, tiny coffee cup, brick wall, nap blanket, heart, camera, calendar, sticker, star. Rounded square bases, soft 3D glassy Y2K material, consistent lighting, simple icon labels optional.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-retro-icons.md",
        "sourceCaseId": "dog-reference/20-retro-icons",
        "sourceRepository": "curated-reference-examples"
    },
    {
        "id": "reference-dog/bento-memory-card/1",
        "title": "Bento 记忆卡",
        "categoryId": "reference-dog",
        "categoryLabel": "小狗案例",
        "categoryAccent": "#6E8B5B",
        "templateRef": "reference-examples/dog-reference/dog-bento-memory-card.md",
        "templateLabel": "Bento Memory Card",
        "promptHint": "小狗参考照片风格 prompt：Bento 记忆卡。",
        "promptContent": "Use the attached reference photo as the identity and content anchor. Preserve the recognizable subject, core colors, and emotional atmosphere, but reinterpret it in the requested visual format. Keep the result polished and intentional. Avoid random extra logos, watermarks, QR codes, timestamps, broken text, unreadable dense copy, duplicate faces, distorted anatomy, and clutter. If a layout normally needs text, use clean placeholder typography or very short simple English labels only, never dense paragraphs.\nCreate a warm bento-grid memory card about this sleepy cafe dog. Use 7-8 rounded modules: large hero dog module, paw detail, color palette, tiny mood note block, sofa texture, cafe light, little heart icon, date placeholder. Apple-newsroom meets diary scrapbook, visual-heavy, minimal placeholder text.",
        "promptPath": "garden-gpt-image-2/prompt/batch-suitable-20260705-191705/dog-bento-memory-card.md",
        "sourceCaseId": "dog-reference/21-bento-memory-card",
        "sourceRepository": "curated-reference-examples"
    }
];
