// Generated from the pinned image-effects build snapshot. Do not edit entries by hand.

export type ImageStylePreviewEntry = {
    fileName: `${string}.jpg` | `${string}.png`;
    sourceSet: 'image-effects-snapshot' | 'gpt-image-2-101' | 'curated-reference-examples' | 'github-skill';
    sourceCaseId: string;
    sourceIndex: number;
    width: number;
    height: number;
};

export const IMAGE_STYLE_PREVIEW_MANIFEST: Record<string, ImageStylePreviewEntry> = {
    'image-effects/anime-key-visual@1.0.0': { fileName: 'anime-key-visual.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'anime-key-visual@1.0.0', sourceIndex: 1, width: 768, height: 1024 },
    'image-effects/anime-pitch-board@1.0.0': { fileName: 'anime-pitch-board.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'anime-pitch-board@1.0.0', sourceIndex: 2, width: 1440, height: 900 },
    'image-effects/background-replacement@1.0.0': { fileName: 'background-replacement.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'background-replacement@1.0.0', sourceIndex: 3, width: 1440, height: 900 },
    'image-effects/banner-grid-2x2@1.0.0': { fileName: 'banner-grid-2x2.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'banner-grid-2x2@1.0.0', sourceIndex: 4, width: 1024, height: 1024 },
    'image-effects/banner-hero@1.0.0': { fileName: 'banner-hero.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'banner-hero@1.0.0', sourceIndex: 5, width: 1024, height: 576 },
    'image-effects/bento-grid-infographic@1.0.0': { fileName: 'bento-grid-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'bento-grid-infographic@1.0.0', sourceIndex: 6, width: 655, height: 1024 },
    'image-effects/bento-memory-card@1.0.0': { fileName: 'bento-memory-card.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'bento-memory-card@1.0.0', sourceIndex: 7, width: 1024, height: 1024 },
    'image-effects/beverage-label-design@1.0.0': { fileName: 'beverage-label-design.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'beverage-label-design@1.0.0', sourceIndex: 8, width: 1440, height: 900 },
    'image-effects/bilingual-layout-visual@1.0.0': { fileName: 'bilingual-layout-visual.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'bilingual-layout-visual@1.0.0', sourceIndex: 9, width: 1440, height: 900 },
    'image-effects/brand-identity-board@1.0.0': { fileName: 'brand-identity-board.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'brand-identity-board@1.0.0', sourceIndex: 10, width: 1440, height: 900 },
    'image-effects/brand-poster@1.0.0': { fileName: 'brand-poster.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'brand-poster@1.0.0', sourceIndex: 11, width: 819, height: 1024 },
    'image-effects/campaign-kv@1.0.0': { fileName: 'campaign-kv.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'campaign-kv@1.0.0', sourceIndex: 12, width: 819, height: 1024 },
    'image-effects/character-grid-portrait@1.0.0': { fileName: 'character-grid-portrait.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'character-grid-portrait@1.0.0', sourceIndex: 13, width: 1024, height: 1024 },
    'image-effects/character-merch-board@1.0.0': { fileName: 'character-merch-board.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'character-merch-board@1.0.0', sourceIndex: 14, width: 1024, height: 683 },
    'image-effects/character-relationship-diagram@1.0.0': { fileName: 'character-relationship-diagram.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'character-relationship-diagram@1.0.0', sourceIndex: 15, width: 1440, height: 900 },
    'image-effects/character-sheet@1.0.0': { fileName: 'character-sheet.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'character-sheet@1.0.0', sourceIndex: 16, width: 1024, height: 683 },
    'image-effects/chat-interface-scene@1.0.0': { fileName: 'chat-interface-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'chat-interface-scene@1.0.0', sourceIndex: 17, width: 1440, height: 900 },
    'image-effects/cinematic-storyboard@1.0.0': { fileName: 'cinematic-storyboard.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'cinematic-storyboard@1.0.0', sourceIndex: 18, width: 1024, height: 1024 },
    'image-effects/comparison-infographic@1.0.0': { fileName: 'comparison-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'comparison-infographic@1.0.0', sourceIndex: 19, width: 1440, height: 900 },
    'image-effects/concept-scene@1.0.0': { fileName: 'concept-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'concept-scene@1.0.0', sourceIndex: 20, width: 1024, height: 512 },
    'image-effects/cosmetic-packaging@1.0.0': { fileName: 'cosmetic-packaging.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'cosmetic-packaging@1.0.0', sourceIndex: 21, width: 1440, height: 900 },
    'image-effects/cultural-portrait-series@1.0.0': { fileName: 'cultural-portrait-series.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'cultural-portrait-series@1.0.0', sourceIndex: 22, width: 1440, height: 900 },
    'image-effects/dense-explainer-slides@1.0.0': { fileName: 'dense-explainer-slides.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'dense-explainer-slides@1.0.0', sourceIndex: 23, width: 1440, height: 900 },
    'image-effects/editorial-cover@1.0.0': { fileName: 'editorial-cover.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'editorial-cover@1.0.0', sourceIndex: 24, width: 768, height: 1024 },
    'image-effects/educational-diagram-slide@1.0.0': { fileName: 'educational-diagram-slide.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'educational-diagram-slide@1.0.0', sourceIndex: 25, width: 1440, height: 900 },
    'image-effects/er-diagram@1.0.0': { fileName: 'er-diagram.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'er-diagram@1.0.0', sourceIndex: 26, width: 1440, height: 900 },
    'image-effects/exploded-view-poster@1.0.0': { fileName: 'exploded-view-poster.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'exploded-view-poster@1.0.0', sourceIndex: 27, width: 1440, height: 900 },
    'image-effects/flowchart-decision@1.0.0': { fileName: 'flowchart-decision.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'flowchart-decision@1.0.0', sourceIndex: 28, width: 1440, height: 900 },
    'image-effects/food-map@1.0.0': { fileName: 'food-map.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'food-map@1.0.0', sourceIndex: 29, width: 1024, height: 1024 },
    'image-effects/founder-portrait@1.0.0': { fileName: 'founder-portrait.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'founder-portrait@1.0.0', sourceIndex: 30, width: 1440, height: 900 },
    'image-effects/four-panel-comic@1.0.0': { fileName: 'four-panel-comic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'four-panel-comic@1.0.0', sourceIndex: 31, width: 1024, height: 1024 },
    'image-effects/game-screenshot-mockup@1.0.0': { fileName: 'game-screenshot-mockup.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'game-screenshot-mockup@1.0.0', sourceIndex: 32, width: 1440, height: 900 },
    'image-effects/graphical-abstract@1.0.0': { fileName: 'graphical-abstract.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'graphical-abstract@1.0.0', sourceIndex: 33, width: 1440, height: 900 },
    'image-effects/hand-drawn-infographic@1.0.0': { fileName: 'hand-drawn-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'hand-drawn-infographic@1.0.0', sourceIndex: 34, width: 655, height: 1024 },
    'image-effects/healing-anime-scribble-v3@1.0.0': { fileName: 'healing-anime-scribble-v3.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'healing-anime-scribble-v3@1.0.0', sourceIndex: 35, width: 1448, height: 1086 },
    'image-effects/healing-scene@1.0.0': { fileName: 'healing-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'healing-scene@1.0.0', sourceIndex: 36, width: 683, height: 1024 },
    'image-effects/illustrated-city-map@1.0.0': { fileName: 'illustrated-city-map.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'illustrated-city-map@1.0.0', sourceIndex: 37, width: 1440, height: 900 },
    'image-effects/kpi-dashboard-infographic@1.0.0': { fileName: 'kpi-dashboard-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'kpi-dashboard-infographic@1.0.0', sourceIndex: 38, width: 1440, height: 900 },
    'image-effects/legend-heavy-infographic@1.0.0': { fileName: 'legend-heavy-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'legend-heavy-infographic@1.0.0', sourceIndex: 39, width: 1440, height: 900 },
    'image-effects/lifestyle-product-scene@1.0.0': { fileName: 'lifestyle-product-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'lifestyle-product-scene@1.0.0', sourceIndex: 40, width: 1024, height: 768 },
    'image-effects/live-commerce-ui@1.0.0': { fileName: 'live-commerce-ui.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'live-commerce-ui@1.0.0', sourceIndex: 41, width: 1440, height: 900 },
    'image-effects/local-object-replacement@1.0.0': { fileName: 'local-object-replacement.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'local-object-replacement@1.0.0', sourceIndex: 42, width: 1440, height: 900 },
    'image-effects/lookbook-grid@1.0.0': { fileName: 'lookbook-grid.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'lookbook-grid@1.0.0', sourceIndex: 43, width: 768, height: 1024 },
    'image-effects/manga-spread-page@1.0.0': { fileName: 'manga-spread-page.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'manga-spread-page@1.0.0', sourceIndex: 44, width: 1024, height: 703 },
    'image-effects/mascot-brand-kit@1.0.0': { fileName: 'mascot-brand-kit.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'mascot-brand-kit@1.0.0', sourceIndex: 45, width: 683, height: 1024 },
    'image-effects/mechanism-diagram@1.0.0': { fileName: 'mechanism-diagram.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'mechanism-diagram@1.0.0', sourceIndex: 46, width: 1440, height: 900 },
    'image-effects/method-pipeline-overview@1.0.0': { fileName: 'method-pipeline-overview.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'method-pipeline-overview@1.0.0', sourceIndex: 47, width: 1440, height: 900 },
    'image-effects/mind-map-tech@1.0.0': { fileName: 'mind-map-tech.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'mind-map-tech@1.0.0', sourceIndex: 48, width: 1440, height: 900 },
    'image-effects/minimal-zine-poster@1.0.0': { fileName: 'minimal-zine-poster.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'minimal-zine-poster@1.0.0', sourceIndex: 49, width: 1024, height: 1536 },
    'image-effects/minimalist-mood-scene@1.0.0': { fileName: 'minimalist-mood-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'minimalist-mood-scene@1.0.0', sourceIndex: 50, width: 683, height: 1024 },
    'image-effects/mixed-style-multi-panel@1.0.0': { fileName: 'mixed-style-multi-panel.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'mixed-style-multi-panel@1.0.0', sourceIndex: 51, width: 1024, height: 1024 },
    'image-effects/multi-condition-comparison@1.0.0': { fileName: 'multi-condition-comparison.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'multi-condition-comparison@1.0.0', sourceIndex: 52, width: 1440, height: 900 },
    'image-effects/network-topology@1.0.0': { fileName: 'network-topology.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'network-topology@1.0.0', sourceIndex: 53, width: 1440, height: 900 },
    'image-effects/neural-network-architecture@1.0.0': { fileName: 'neural-network-architecture.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'neural-network-architecture@1.0.0', sourceIndex: 54, width: 1440, height: 900 },
    'image-effects/object-removal@1.0.0': { fileName: 'object-removal.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'object-removal@1.0.0', sourceIndex: 55, width: 1440, height: 900 },
    'image-effects/packaging-showcase@1.0.0': { fileName: 'packaging-showcase.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'packaging-showcase@1.0.0', sourceIndex: 56, width: 1024, height: 768 },
    'image-effects/photo-illustration-diptych@1.0.0': { fileName: 'photo-illustration-diptych.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'photo-illustration-diptych@1.0.0', sourceIndex: 57, width: 1024, height: 1536 },
    'image-effects/photo-illustration-diptych-lakeside@1.0.0': { fileName: 'photo-illustration-diptych-lakeside.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'photo-illustration-diptych-lakeside@1.0.0', sourceIndex: 58, width: 1024, height: 1536 },
    'image-effects/photo-illustration-editorial-echo@1.0.0': { fileName: 'photo-illustration-editorial-echo.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'photo-illustration-editorial-echo@1.0.0', sourceIndex: 59, width: 1024, height: 768 },
    'image-effects/picture-book-scene@1.0.0': { fileName: 'picture-book-scene.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'picture-book-scene@1.0.0', sourceIndex: 60, width: 1024, height: 683 },
    'image-effects/policy-style-slide@1.0.0': { fileName: 'policy-style-slide.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'policy-style-slide@1.0.0', sourceIndex: 61, width: 1440, height: 900 },
    'image-effects/portrait-local-edit@1.0.0': { fileName: 'portrait-local-edit.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'portrait-local-edit@1.0.0', sourceIndex: 62, width: 1440, height: 900 },
    'image-effects/premium-studio-product@1.0.0': { fileName: 'premium-studio-product.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'premium-studio-product@1.0.0', sourceIndex: 63, width: 1024, height: 768 },
    'image-effects/product-card-overlay@1.0.0': { fileName: 'product-card-overlay.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'product-card-overlay@1.0.0', sourceIndex: 64, width: 1440, height: 900 },
    'image-effects/product-retouching@1.0.0': { fileName: 'product-retouching.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'product-retouching@1.0.0', sourceIndex: 65, width: 1440, height: 900 },
    'image-effects/product-tvc-storyboard@1.0.0': { fileName: 'product-tvc-storyboard.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'product-tvc-storyboard@1.0.0', sourceIndex: 66, width: 1024, height: 683 },
    'image-effects/professional-portrait@1.0.0': { fileName: 'professional-portrait.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'professional-portrait@1.0.0', sourceIndex: 67, width: 1440, height: 900 },
    'image-effects/publication-chart@1.0.0': { fileName: 'publication-chart.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'publication-chart@1.0.0', sourceIndex: 68, width: 1440, height: 900 },
    'image-effects/qualitative-comparison-grid@1.0.0': { fileName: 'qualitative-comparison-grid.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'qualitative-comparison-grid@1.0.0', sourceIndex: 69, width: 1440, height: 900 },
    'image-effects/recipe-process-flowchart@1.0.0': { fileName: 'recipe-process-flowchart.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'recipe-process-flowchart@1.0.0', sourceIndex: 70, width: 683, height: 1024 },
    'image-effects/research-overview-poster@1.0.0': { fileName: 'research-overview-poster.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'research-overview-poster@1.0.0', sourceIndex: 71, width: 1440, height: 900 },
    'image-effects/retro-skeuomorphic-icons@1.0.0': { fileName: 'retro-skeuomorphic-icons.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'retro-skeuomorphic-icons@1.0.0', sourceIndex: 72, width: 1024, height: 1024 },
    'image-effects/scene-distillation-zine@1.0.0': { fileName: 'scene-distillation-zine.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'scene-distillation-zine@1.0.0', sourceIndex: 73, width: 1024, height: 1536 },
    'image-effects/scenes-gathered-zine@1.0.0': { fileName: 'scenes-gathered-zine.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'scenes-gathered-zine@1.0.0', sourceIndex: 74, width: 1024, height: 1536 },
    'image-effects/scenes-gathered-zine-sea@1.0.0': { fileName: 'scenes-gathered-zine-sea.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'scenes-gathered-zine-sea@1.0.0', sourceIndex: 75, width: 1536, height: 1024 },
    'image-effects/scientific-schematic@1.0.0': { fileName: 'scientific-schematic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'scientific-schematic@1.0.0', sourceIndex: 76, width: 1440, height: 900 },
    'image-effects/sequence-diagram@1.0.0': { fileName: 'sequence-diagram.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'sequence-diagram@1.0.0', sourceIndex: 77, width: 1440, height: 900 },
    'image-effects/short-video-cover-ui@1.0.0': { fileName: 'short-video-cover-ui.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'short-video-cover-ui@1.0.0', sourceIndex: 78, width: 1440, height: 900 },
    'image-effects/social-interface-mockup@1.0.0': { fileName: 'social-interface-mockup.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'social-interface-mockup@1.0.0', sourceIndex: 79, width: 1440, height: 900 },
    'image-effects/state-machine@1.0.0': { fileName: 'state-machine.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'state-machine@1.0.0', sourceIndex: 80, width: 1440, height: 900 },
    'image-effects/step-by-step-infographic@1.0.0': { fileName: 'step-by-step-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'step-by-step-infographic@1.0.0', sourceIndex: 81, width: 683, height: 1024 },
    'image-effects/sticker-set@1.0.0': { fileName: 'sticker-set.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'sticker-set@1.0.0', sourceIndex: 82, width: 1024, height: 683 },
    'image-effects/store-distribution-map@1.0.0': { fileName: 'store-distribution-map.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'store-distribution-map@1.0.0', sourceIndex: 83, width: 1440, height: 900 },
    'image-effects/style-transfer-selfie@1.0.0': { fileName: 'style-transfer-selfie.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'style-transfer-selfie@1.0.0', sourceIndex: 84, width: 1440, height: 900 },
    'image-effects/system-architecture@1.0.0': { fileName: 'system-architecture.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'system-architecture@1.0.0', sourceIndex: 85, width: 1440, height: 900 },
    'image-effects/themed-3d-icon@1.0.0': { fileName: 'themed-3d-icon.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'themed-3d-icon@1.0.0', sourceIndex: 86, width: 1024, height: 1024 },
    'image-effects/title-safe-poster@1.0.0': { fileName: 'title-safe-poster.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'title-safe-poster@1.0.0', sourceIndex: 87, width: 1440, height: 900 },
    'image-effects/torn-paper-editorial-photo-collage@1.0.0': { fileName: 'torn-paper-editorial-photo-collage.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'torn-paper-editorial-photo-collage@1.0.0', sourceIndex: 88, width: 615, height: 1024 },
    'image-effects/travel-route-map@1.0.0': { fileName: 'travel-route-map.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'travel-route-map@1.0.0', sourceIndex: 89, width: 1440, height: 900 },
    'image-effects/vintage-editorial-infographic@1.0.0': { fileName: 'vintage-editorial-infographic.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'vintage-editorial-infographic@1.0.0', sourceIndex: 90, width: 683, height: 1024 },
    'image-effects/vintage-film-editorial@1.0.0': { fileName: 'vintage-film-editorial.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'vintage-film-editorial@1.0.0', sourceIndex: 91, width: 1024, height: 768 },
    'image-effects/virtual-host@1.0.0': { fileName: 'virtual-host.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'virtual-host@1.0.0', sourceIndex: 92, width: 1440, height: 900 },
    'image-effects/visual-report-page@1.0.0': { fileName: 'visual-report-page.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'visual-report-page@1.0.0', sourceIndex: 93, width: 1440, height: 900 },
    'image-effects/white-background-product@1.0.0': { fileName: 'white-background-product.jpg', sourceSet: 'image-effects-snapshot', sourceCaseId: 'white-background-product@1.0.0', sourceIndex: 94, width: 1024, height: 768 },
};
