const IDENTITY_LOCK = `Use exactly one user-supplied source image. Preserve the adult subject's recognizable identity, facial structure, age, skin tone, hairstyle, pose, clothing, accessories, hands, props, camera angle, crop, and location geometry. Treat the supplied image as the only source of identity and composition. Do not replace the person, beautify them into a different face, add text, logos, borders, watermarks, extra people, extra limbs, or unrelated objects.`;

export const PHOTO_TO_STYLED_MOTION_PROMPTS = {
    'japanese-cinema-film': `${IDENTITY_LOCK} Restyle it as a contemporary Japanese live-action cinema still with natural photographic likeness, restrained 35mm grain, soft practical lighting, a quiet observational mood, realistic skin texture, muted balanced color, gently lifted blacks, and shallow but believable depth of field. Preserve the original location and adult proportions. This is a photographic film look, not animation.`,
    'handdrawn-anime-film': `${IDENTITY_LOCK} Restyle it as a high-fidelity Japanese animated feature-film frame with refined 2D hand drawing, soft variable pencil-and-ink contours, clean cel-painted skin and fabric, watercolor-gouache background texture, subtle film grain, and nuanced adult facial acting. Preserve realistic facial proportions and recognizable identity. Avoid named studios or artists, oversized eyes, childlike proportions, 3D, and glossy vector rendering.`,
    '90s-cel-animation': `${IDENTITY_LOCK} Restyle it as premium 1990s hand-inked cel animation with confident dark contours, elegant two-step cel shading, a hand-painted background, subtle analog grain and registration texture, sophisticated adult character design, and a restrained palette. Keep the source setting readable and the subject's adult proportions intact. Avoid modern glossy anime, neon overload, chibi anatomy, and plastic 3D rendering.`,
    'seinen-manga-bw': `${IDENTITY_LOCK} Restyle it as a professional black-and-white adult manga splash image with precise likeness, controlled contour variation, feathered shadows, stable halftone screentones, sparse cross-hatching, crisp whites, deep blacks, and pure grayscale. Keep the original pose and environment legible through disciplined line weight and tonal separation. Avoid color, exaggerated cartoon anatomy, text balloons, captions, and decorative page furniture.`,
    'cyberpunk-graphic-novel': `${IDENTITY_LOCK} Restyle it as a high-end color graphic novel with bold clean ink contours, painterly cel shading, selective halftone, realistic adult proportions, cyan edge light, and restrained magenta reflection while keeping the face warm and readable. Keep the original location recognizable. Do not add armor, implants, weapons, futuristic text, or unrelated architecture unless they already exist in the source.`,
    'abstract-screenprint-collage': `${IDENTITY_LOCK} Restyle it as an experimental editorial screen print, risograph, and cut-paper collage. Simplify the face into asymmetrical geometric planes, hair into jagged shards, clothing into overlapping paper shapes, and the background into sparse architectural bars, circles, silhouettes, and negative space. Use five dominant inks: warm peach, signal red, cobalt blue, carbon black, and off-white. Use flat ink coverage with tactile registration texture; no gradients or photorealistic skin.`,
    'ink-wash-portrait': `${IDENTITY_LOCK} Restyle it as a contemporary East Asian ink-wash portrait with recognizable adult likeness and realistic proportions, layered black and charcoal brushwork, soft mineral-gray washes, a restrained cinnabar accent, generous paper texture, and controlled negative space. Keep the source scene recognizable through simplified silhouettes. Avoid calligraphy, seals, text, fantasy costumes, decorative borders, and indiscriminate ink splashes across the face.`,
    'vintage-editorial-film': `${IDENTITY_LOCK} Restyle it as a premium 1970s-1990s editorial film photograph with natural likeness, tactile 35mm grain, subtle flash or window-light falloff, realistic fabric and skin, a slightly faded but balanced palette, and authentic magazine portrait composition. Preserve the real location, clothing, pose, and adult proportions. Do not add a printed masthead, caption, border, fake magazine layout, heavy light leaks, or synthetic beauty-filter skin.`,
    'cinematic-realism': `${IDENTITY_LOCK} Restyle it as a high-end live-action cinematic portrait while preserving exact photographic identity, skin texture, pose, clothing, accessories, and location geometry. Use controlled key light, believable practical reflections, refined contrast, and a subtle filmic color grade. Keep hands, glasses, props, and background stable. No illustration treatment, fantasy additions, face reshaping, over-sharpening, or synthetic beauty-filter skin.`,
} as const;
